export const myRecipes = [
  {
    name: "Gai Dan Guo",
    ingredients: [
      "- 8 large eggs",
      "- 100g cake flour",
      "- 2,5tsp corn starch",
      "- 120g icing sugar",
      "- 200g milk",
      "- 1tsp vanilla extract",
      "- a sprinkle of salt",
      "- 0,5tsp creme of tartar",
      "- **********Optionally********** your favourite toppings",
    ],
    instructions: [
      "- Tangzhong | In a pan, combine the oil and milk. Then turn on the heat and slowly whisk in the flour, ensuring the mixture has no clumps. Whisk this mixture continuously with the heat on until the utensil leaves a trail in the tangzhong mixture. Finally, set aside to cool.",
      "- Egg Separation | In two bowls, separate the egg yolks and whites.",
      "- Meringue Mixture | Whisk the egg whites until a soft peak forms, then gently incorporate the sugar and creme of tartar, and continue whisking until stiff peaks form.",
      "- Egg Yolks | When the tangzhong has cooled, incorporate the egg yolks.",
      "- Preheat Oven | Preheat the oven to 160 degrees Celsius.",
      "- Batter | Take a scoop of the meringue mixture (about one third), and gently fold it into the tangzhong mixture. Then fold all of the tangzhong mixture into the meringue mixture. Once the two mixtures have been sufficiently combined, pour the batter into a lined cake pan.",
      "- Bake | Place the cake pan into a baking tray, and fill the tray with hot water. Steam the cake batter for 45 minutes, then remove the cake from the water filled tray, and bake for a further 20-45 minutes or until golden brown.",
      "- Shock The Cake | When the cake has finished baking, firmly tap the cake pan against a hard surface, and let the cake cool upside down on a baking tray.",
      "- Toppings | Once the cake has cooled, add your favourite toppings.",
    ],
    image: require("../assets/cake.png"),
  },
  {
    name: "Crispy Chili Beef",
    ingredients: [
      "Serves 2",
      "- 360g beef",
      "- 3 tbsp soya sauce",
      "- 1 tbsp gochujang paste",
      "- 1 tbsp tomato sauce",
      "- 2 cloves of garlic (minced)",
      "- 1 tbsp rice wine vinegar",
      "- 1 tsp toasted sesame oil",
      "- 1 tbsp sugar",
      "- 1 medium egg",
      "- 3 tbsp corn flour",
      "- Oil for frying (enough to shallow fry)",
      "- **********Optionally********** a scoop of rice, spring onion and sesame seeds",
    ],
    instructions: [
      "- Cut | Cut the beef into strips of whatever length is desired.",
      "- Coat | In a bowl, cover the beef strips with the egg, and then coat the strips in the corn flour.",
      "- Fry | In a wok or pot, heat up the frying oil and cook the beef. The beef should immediately begin sizzling and cooking when it comes into contact with the oil.",
      "- Sauce | Whilst the beef is cooking, combine the soya sauce, gochujang paste, tomato sauce, minced garlic, rice wine vinegar, sesame oil, and sugar in a small bowl and set aside.",
      "- Coat | Once the beef is cooked and golden brown, coat the strips in the sauce.",
      "- Plating | Once all the strips are coated, place them in a bowl on a scoop of rice, and sprinkle some cut spring onion and sesame seeds on top.",
    ],
    image: require("../assets/beef.png"),
  },
  {
    name: "Brownie Cookie",
    ingredients: [
      "- 1 cup cocoa",
      "- 2 cups sugar (brown/white)",
      "- 225g unsalted butter",
      "- 6tsp oil",
      "- 2 eggs",
      "- 4tsp vanilla essence",
      "- 3 cups flour",
      "- 1tsp baking powder",
      "- 1tsp salt",
      "- 1 cup chocolate chips",
    ],
    instructions: [
      "- Preheat Oven | Preheat the oven to 180 degrees Celsius.",
      "- Dough | In a bowl, mix the cocoa, flour, sugar, baking powder and salt together. Then add the oil, eggs, and vanilla essence, stirring well so tat there are no clumps. Finally, add your chocolate chips.",
      "- Bake | On a lined baking tray, place a scoop of cookie dough and shape it into desired shape. Then bake for 10 minutes, and let cool on a cooling rack.",
    ],
    image: require("../assets/cookie_fudge.png"),
  },
  {
    name: "Choc-Chip Cookie",
    ingredients: [
      "- 225g unsalted butter",
      "- 150g castor sugar",
      "- 330g brown sugar",
      "- 2tsp espresso powder",
      "- 2tsp salt",
      "- 0.5tsp baking soda",
      "- 315g flour",
      "- 150g dark chocolate (50-70% dark chocolate)",
      "- any amount of chocolate chips",
      "- ***********optionally*********** flaky salt to decorate",
    ],
    instructions: [
      "- Browned Butter | Simmer the butter in a pot until it becomes dark brown, and smells nutty. Then set aside and allow to cool.",
      "- Dough | In a mixing bowl, combine castor sugar, brown sugar, salt, espresso powder, baking soda, and eggs, then mix together until combined. Then add your browned butter, along with the flour, and mix again.",
      "- Freeze | Line your baking tray with baking paper. Then scoop your cooking dough onto the tray, and shape into balls. When all your cookie dough has been made into balls, put cling wrap over the dough, and let it rest for up to 3 days in the fridge. ",
      "- Bake | Heat the oven to 160 degrees Celsius, and remove the cling wrap. Bake the cookie dough from cold for 18-20 minutes, or until golden brown. ",
    ],
    image: require("../assets/cookie.png"),
  },
  {
    name: "Lemonade",
    ingredients: [
      "Serves 5",
      "- 4 limes",
      "- 0,5 cups sweetened condensed milk (more if you want it sweeter)",
      "- 4 cups water",
      "- **********Optionally********** ice and lime slices to serve",
    ],
    instructions: [
      "- Cut | Slice the 4 limes into pieces that can fit in the blender.",
      "- Blend | Blend the sliced limes with the water and sweetened condensed milk. Do not blend for too long as this will make the lemonade bitter.",
      "- Strain | Take the lemonade, and pour it through a strainer to get rid of the pulp. Make sure that the liquid is strained into a jug.",
      "- Serve | Fill a cup with ice and pour the lemonade in. Garish the rim of the cup with a slice of lime or place a lime rind on top of the drink.",
    ],
    image: require("../assets/lemonade.png"),
  },
  {
    name: "Chili Oil Pasta",
    ingredients: [
      "Serves 2-3",
      "- 1 tbsp unsalted butter",
      "- 1 tbsp honey",
      "- 1 tbsp soya sauce",
      "- 1 tbsp chili oil",
      "- 1 tbsp minced garlic",
      "- 2 portions of spaghetti (around 120-200g)",
      "- Salt",
      "- Oil",
      "- *****Optional***** grated cheese for toppings",
    ],
    instructions: [
      "- Pasta | Fill a large pot with water, and bring it to a boil. Season the water with a dash of salt and oil, and put in your spaghetti. When the spaghetti is al dante, pour out the spaghetti water, keeping 1 tbsp aside.",
      "- Sauce | In a small pan, melt the butter and add the minced garlic. Let this cook for about a minute before adding the honey, soya sauce, chili oil and spaghetti water. The sauce is done when a spoon can leave a trail through the sauce." <
        "- Combine | Pour the sauce over the cooked spaghetti, and mix until the sauce covers the spaghetti.",
      "- Serve | In a serving bowl, add your sauce covered spaghetti, along with a sprinkle of cheese on top.",
    ],
    image: require("../assets/chili.png"),
  },
  {
    name: "Blueberry Cake",
    ingredients: [
      "- 1 cup granulated sugar",
      "- 1/2 cup unsalted butter",
      "- 2 large eggs",
      "- 1 tbsp lemon zest",
      "- 2 tbsp lemon juice",
      "- 0,5 tsp salt",
      "- 1,5 cups flour",
      "- 1 tsp baking powder",
      "- 0,5 cup milk",
      "- 1 cup blueberries",
      "- **********Optionally********** some lemon flavoured icing, and blueberries",
    ],
    instructions: [
      "- Preheat Oven | Preheat the oven to 180 degrees Celsius.",
      "- Coat | In a bowl, lightly coat the blueberries in some flour.",
      "- Creaming | In a different bowl, cream the sugar and butter together until light and fluffy.",
      "- Batter | In the same bowl as the creamed butter and sugar, fold in the eggs, lemon juice, lemon zest and milk. Then fold in the salt, flour, and baking powder. Finally, add fold in the flour coated blueberries.",
      "- Bake | Bake the batter in a lined loaf pan for 55-65 minutes, or until golden brown and cooked in the center.",
      "- Topping | Once the cake has cooled, coat the top with the lemon flavoured icing and blueberries.",
    ],
    image: require("../assets/cake_lemon.png"),
  },
  {
    name: "Hotteok",
    ingredients: [
      "Makes 8 (size dependent)",
      "- 2,5 tsp active dry yeast (about one packet)",
      "- 1/4 cup warm water",
      "- 1 tsp sugar",
      "- 2 cups flour",
      "- 1 tbsp oil",
      "- 1 and 1/4 cups milk",
      "- 0,5 cup of brown sugar",
      "- 1 tsp cinnamon powder",
      "- Oil for frying",
      "- ***********Optionally*********** 10 tbsp assorted roasted nuts (almonds and hazelnuts are the most popular)",
      "- ***********Optionally*********** 0,5 cup of glutinous rice flower",
    ],
    instructions: [
      "- Yeast Activation | In a bowl, mix together the yeast, sugar (1tsp) and water, and let it rest for 10 minutes.",
      "- Batter | In the same bowl as the yeast mixture, add the milk and oil, an mix together. Then add the flour, and salt, and mix until combined.",
      "- 1st Rise | Cover the batter bowl with cling wrap and let rest for 1 hour.",
      "- 2nd Rise | After 1 hour, deflate the batter, and let rise again for 30 minutes.",
      "- Filling | In a bowl, combine the cinnamon, sugar (0,5 cup) and nuts. Once the batter has finished rising the second time, take a scoop of batter and flatten into a circle. Then make make the circle into a bowl shape, and fill it with filling. Finally, close the circle, pinching around the edges to seal.",
      "- Repeat | Continue filling dough circles until there is no more batter or filling.",
      "- Fry | Coat the bottom of a frying pan with some oil, and then place your filled hotteok onto it. As it cooks, flatten the hotteok with a spatula. The hotteok is cooked when both sides are golden brown.",
      "- Serve | Hotteok is ready to eat straight off the pan, but could be accompanied by an extra sprinkle of nuts on top.",
    ],
    image: require("../assets/pancakes.png"),
  },
];

export const mySkills = [
  {
    name: "Cutting Skills",
    introduction: [
      "In this lesson, you will learn the various ways that things can be cut, and how to do it. This includes dicing, chiffonade, julienne and mincing. I suggest that you use a sharp non-serrated knife for this exercise, and choose veggies such as onions for dicing, leafy herbs for chiffonade, carrots for julienne and garlic gloves for mincing. Whilst these cuts can be applied to different vegetables, I have found that the above suggested ones, are the easiest to practice with",
    ],
    instructions: [
      [
        "Dicing:",

        "This method is used to ensure that the ingredient is cut in a way which allows for all the pieces to be equal sizes so that it can cook evenly. I also like to call this method the cubing method, because the cut ingredient’s pieces are in the shape of cubes.",

        "***********This example uses an peeled onion***********",
        "- Step 1 | Taking your onion, cut the onion in half through the root end, and place the onion flat side down.",
        "- Step 2 | On the side furthest from the root **(the tip)**, make horizontal cuts towards the root without cutting the root.",
        "- Step 3 | Starting at the tip again, make vertical slices towards the root, without cutting the root.",
        "- Step 4 | Finally, make vertical cuts from the tip of the onion to the root of the onion, such that your cuts in this step are perpendicular to the cuts made in step 3.",
        "- Step 5 | Repeat for the other half.",
        "Note: The more vertical and horizontal slices you make, the smaller your diced vegetable pieces will be.",
      ],
      [],
    ],
  },
];
